M48
; DRILL file {KiCad 7.0.6} date Thu Jul 27 21:49:21 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-27T21:49:21+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0454
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1575
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1654
%
G90
G05
T1
X1.9299Y-2.9528
X2.9528Y-1.1811
X3.9756Y-2.9528
T2
X2.0121Y-2.2798
X3.7711Y-2.8347
T3
X2.2987Y-1.7081
X3.8461Y-2.1228
T4
X2.713Y-3.2553
T0
M30
